### ISSUE TITLE
Pre TechED 2018 mission : Deploy your app to Fiori Launchpad Marker.js error

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#2588]
Hello Meredith,

I am getting below error when I am launching my Pre techEd2018 lottery application from Fiori launchpad.

Error: failed to load 'sap/m/markers.js' from https://sapui5.hana.ondemand.com/1.40.18/resources/sap/m/markers.js

@mhassett92 

Please refer the attached screenshot.
![marker js error](https://user-images.githubusercontent.com/42535599/44744226-40406580-ab22-11e8-99a2-a0afd870561a.JPG)

**Comment by amitcruz** [comment]
When I am trying to run the Pre TechEd 2018 lottery application from WEBIDE using FLP Sandbox I am getting below error 

HTTP request failed 500
Service exception: [414] user is forced to change password

It seems password of HANA xsodata is changed . Please look at it.

**Comment by mhassett92** [comment]
The 414 service error should be resolved.

**Comment by amitcruz** [comment]
Thanks Meredith for quick response. Waiting for the fix.

**Comment by mhassett92** [comment]
The fix for the 414 error is in place. Please let me know if it is not resolved.

**Comment by amitcruz** [comment]
Hello @mhassett92  , It is not fixed , I am still getting same error . Please check at your end,

**Comment by amitcruz** [comment]
Hello @mhassett92..i am awaiting for your reply. Is it fixed or not?

**Comment by amitcruz** [comment]
Hello Meredith @mhassett92
When can I expect the issue to be resolved. Last day for completing the mission is Sep 10. Please fix it as earliest as possible.

**Comment by AbhijitNilegaonkar** [comment]
AmitCruz, I believe we need to be considerate, patient and polite while requesting support. I believe this is not revenue generating or a paid service by SAP. I do not work for SAP. But I felt above request was little aggressive.  Thanks for understanding.

**Comment by mhassett92** [comment]
The issue is resolved. If you are still having issues, please post more information with screenshots of the error.

**Comment by AbhijitNilegaonkar** [comment]
I guess I am getting the same error.  Don't have screen capture at the moment but will update more details soon. Infact I followed the steps twice to create a second app. I get the same error on both the apps. 'could not open app. Please try again later'

**Comment by mhassett92** [comment]
The issue regarding the marker.js file is related to the SAPUI5 version in your Portal Fiori Launchpad site. There has been a change recently in the code imported from Build that is causing this. To resolve it, go to your FLP site admin page, go to settings, and change the version for SAPUI5 back to Innovation. After you do, republish, and clear the cache, the application should work. Please keep me posted if this solves it. @AbhijitNilegaonkar I believe this will resolve the issue you are seeing in the other issue you opened, but let me know in that issue if things still aren't working after this fix.

Thank you!
Meredith

**Comment by AbhijitNilegaonkar** [comment]
Meredith I will just continue on my thread. Thanks.

**Comment by amitcruz** [comment]
Thanks Meredith for your help.. Please close the thread.

**Comment by amitcruz** [comment]
Thanks Meredith for your timely support and guidance. I am closing the issue.
