### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by MKatsu** [SAPDocuments/Tutorials#4019]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Step4 - 3.
Provision always fails after a few seconds. What could be the reasons?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback.
Dev team is investigating this issue and an internal VH incident has been raised on Friday. Will keep you posted on the progress.
Best Regards, Gautham

**Comment by gauthamkrishna-sap** [comment]
Issue is fixed now. Can you please try the tenant provisioning process again?

Best regards, Gautham

**Comment by MKatsu** [comment]
It worked! Thanks.

**Comment by Shreyashri91** [comment]
Hello Team,

I am facing similar kind of issues with my Tenant provisioning. It is getting stuck after completion of 18 percent. I closed the browser & retried multiple times. But I can see the same problem persists.

Here are my trial account details:

Global Account: 85aa4789trial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.


Please do the needful so that I can set up the tenant provisioning successfully.

Regards
Shreya
![thumbnail_image](https://user-images.githubusercontent.com/65550157/82286830-4cd2b480-99bc-11ea-9c4e-32a61473d993.png)
