### ISSUE TITLE
Modify a Customer Record in an MDK App

### ISSUE THREAD

**Issue by prtkkr** [SAPDocuments/Tutorials#4699]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-edit-customer.html

Please specify the step you are referring to: (Step 6)

While editing customer details, everything is working fine and data is being updated locally but the same details is not updated in the back end.

Logs show the following message: "Finished sending POST request to back end https://mobile-service-sample-odata-v2-espm.cfapps.eu10.hana.ondemand.com/4045a812-dcde-46ac-9c96-9be5f4f89ea9/SampleServices/ESPM.svc/v2/Customers('250f913f-92ba-4d0f-82a0-f12f99381f6c') in 36 ms. HTTP status from the back end is 500."

Please help.

**Comment by jitendrakansal** [comment]
@prtkkr thanks for reporting this issue. We are already aware of it, we are hoping to fix it in upcoming CF release. I'll update this thread once it's there.

**Comment by prtkkr** [comment]
Thank you.

**Comment by prtkkr** [comment]
@jitendrakansal I think the above issue has been fixed. Thank you.

**Comment by prtkkr** [comment]
@jitendrakansal  I was trying to create new entry into the customer table and again the same error is showing up i.e. HTTP 500. While updating part is working fine.

**Comment by jitendrakansal** [comment]
@prtkkr i tried on my side and it works fine (create, update, delete). 
Are you trying on Mobile services trial (CF) ? 
You could RESET sample service dataset to original state? 
![image](https://user-images.githubusercontent.com/31536700/75983265-7cf3d680-5ee8-11ea-8b1b-3ad2e9495a81.png)
Sync in the MDK app, then try creating a record. 
If issue still persists, could you then share your metadata project (right click in WebIDE>Export), i can look at it.

**Comment by prtkkr** [comment]
Thank you @jitendrakansal  for the help within a short period of time. Create function is working now.

**Comment by MiqueiasMaia** [comment]
@jitendrakansal, i've made a createEntity action as the following, linking just one entity:
![image](https://user-images.githubusercontent.com/18472559/136046414-2da332c7-962f-4cd3-8bfe-ce638cba37cc.png)

When I create the DeleteteEntity and try to remove the object, i'm receiving an error "Cannot delete this entity instance. Another entity instance depends on it", but i've created the relation only with the target entity that i'm trying to remove, as you can see:
![image](https://user-images.githubusercontent.com/18472559/136047103-45212073-1128-408a-a55c-bef1bb61a6c0.png)

How can I remove this?
